- htdocs/style.css
- src/html.htl
fixing the ESI issue and making sure `[headers|footers]:empty` are hidden.
> #10 silent continue on error

- README.md
- vcl/extensions.vcl
PR for #1 
This still needs:
- https://github.com/adobe/helix-cli/pull/893
- https://github.com/adobe/helix-publish/pull/93 
to be merged and released to be useful.
> Use vcl extension points

- htdocs/style.css
- package-lock.json
- src/html.pre.js
This would be one alternative for https://github.com/adobe/helix-pages/issues/5
Using "server side" jquery is really nice to shuffle nodes and add classes but does not feel so natural...
Let's debate.
> Use jquery instead of homemade functions

- .circleci/config.yml
PR for #2 
Impossible to test in a branch and on another domain. Needs to validate in production...
Credentials are anyway stored in CircleCI and points to "my" (acapt) Fastly domain and runtime accounts. Should not break production.
> Setup auto-publish

- htdocs/style.css
- src/plain_html.htl
PR for #24 
CSS trick to hide the ugly error message due to invalid ESI response
> Default rendering shows /header.plain.html and /footer.plain.html 

- src/html.pre.js
> small jquery change

- src/html.htl
- src/html.pre.js
Reverts adobe/helix-pages#30
More details in the ticket #29
> Revert "Temporary workaround for ESI cache killer: append query string"

- .circleci/config.yml
> Auto-publish: commit config after publish

- .circleci/config.yml
> Auto publish: push to git

- htdocs/head.html
- src/html.htl
to allow an override of the head section in the `head.html` is externalized and can be overridden in the root folder of the content directory. this should to include javascript and custom css easily.
> externalizing head.html

- htdocs/style.css
- index.md
better handling of incompatible repos and usernames for the URL converter on https://www.project-helix.page/
> initial url validation code

- src/html.pre.js
fixing issue https://github.com/adobe/helix-pages/issues/40
added 'img' class to the first element of a div
> fixed img default layout

- package-lock.json
- package.json
`request` is a peer dependency of `request-promise-native` and needs to be installed separately. See https://github.com/request/request-promise-native#installation.
> Install `request`

- src/html.pre.js
turns out some of the selectors in `html.pre.js` were too greedy and overly inclusive
> improved selectors

- src/html.pre.js
found some more ocases where the `image` selector didn't work right...
> even better selectors

- .circleci/config.yml
- .eslintignore
- README.md
- fstab.json
- google/helix-doc2markdown/.clasp.json
- google/helix-doc2markdown/README.md
- google/helix-doc2markdown/appsscript.json
- google/helix-doc2markdown/main.js
- google/helix-doc2markdown/pollyfills.js
- google/helix-doc2markdown/utils.js
- package-lock.json
- package.json
- src/fetch-fstab.js
- src/fetch-google.js
- src/html.pre.js
> feat(content): Support for google docs mounts

- .circleci/config.yml
- .releaserc.js
- package-lock.json
- package.json
sets up semantic release so that the package number is automatically increased and a change log is written. this is useful for local development to check which helix-pages version is used.
> feat(release): setup semantic-release

- .circleci/config.yml
- README.md
- src/fetch-google.js
- src/html.pre.js
> fix(google): use default service when GOOGLE_DOCS_ROOT is not available

- README.md
Trick to trigger a new publish.
> feat(doc): Remove greenkeeper badge

- package-lock.json
- package.json
- src/idx_json.pipe.js
> fix(deps): use fixed pipeline dependency

- .circleci/config.yml
- src/fetch-external.js
- src/fetch-fstab.js
- src/html.htl
- src/html.pre.js
- test/smoke/homepage.smoke.js
> feat(indexing): include a x-source-hash meta tag for indexing support

- README.md
Outline the steps for quick setup of a helix pages website
from a Google Drive folder.
[trivial] No code changes.
> docs(*): add some docs for automatic publishing [trivial]

- .circleci/config.yml
- htdocs/sitemap.xml
> fix(sitemap): add algolia params to hlx deploy

- cgi-bin/sitemap.js
> fix(sitemap): add x-hlx-pages-host header

- .circleci/config.yml
PR for https://github.com/adobe/helix-pages/issues/179
> feat(log): enable log to Coralogix

- .circleci/config.yml
PR for #195 
Depends on https://github.com/adobe/helix-pipeline/issues/620 but can be merged before.
> feat(epsagon): instrument with Epsagon

- README.md
Change the json example for Google Drive to the YAML format
and add a /g mountpoint.
> docs(*): update fstab example to YAML [trivial]

- .circleci/config.yml
> feat(tests): add theblog smoke tests

- .circleci/config.yml
> chore(test): Require theblog tests

- .circleci/config.yml
- monitoring/error500.js
- test/monitor.test.js
add monitor script to repo, and make tests
> perf(error500.js): house monitor script for pages

- monitoring/error500.js
> Fix module undefined

- .circleci/config.yml
- src/embed_html.htl
- src/embed_html.pre.js
- test/smoke/homepage.smoke.js
PR for #78 
Still want to add corresponding tests
> feat(rendering): support for internal embeds

- src/html.htl
> feat(seo): add twitter tags

- htdocs/style.css
Small styling changes on the pre, Fixed overflow-x, adjusted the font-size on code slightly.
Bad news - I think your courier-to-code fix broke your copy/paste code
> Update style.css to account for overflow-x in code block

- .circleci/config.yml
> refactor(config.yaml): remove monitor deploy

- cgi-bin/sitemap.js
- src/html.pre.js
- src/utils.js
- test/unit/html.pre.test.js
> refactor(metadata): use same host name lookup as in sitemap.xml

- src/html.pre.js
- src/utils.js
- test/unit/html.pre.test.js
- test/unit/sitemap.test.js
> fix(url): improve hostname lookup

- src/html.pre.js
- test/unit/html.pre.test.js
Revert https://github.com/adobe/helix-pages/commit/8a11b44bfb83bdbe2c16648d3410c9bae0350f83
> chore: revert master commit 8a11b44

- src/html.pre.js
- src/utils.js
- test/unit/html.pre.test.js
> fix(seo): make sure image url is absolute

- src/utils.js
- test/unit/html.pre.test.js
- test/unit/sitemap.test.js
> fix(seo): split hlx-forwarded-host list and use first

- robots.txt
> feat(seo): keep robots out by default

- .circleci/config.yml
- README.md
> Epsagon publish CI

- test/smoke/homepage.smoke.js
depends on https://github.com/adobe/helix-publish/pull/497
> feat(publish): use new publish version with blocklist

- htdocs/robots.txt
> feat(seo): keep robots out on fastly instead

- .vscode/settings.json
- cgi-bin/sitemap.js
- htdocs/sitemap.xml
- package-lock.json
- package.json
- test/unit/sitemap.test.js
- test/unit/sitemap/helix-query.yaml
- test/unit/sitemap/query-index.json
> feat(sitemap): Allow sitemap entries to be fed from a json endpoint

- test/pages/pages.test.js
tests timing out, sorry about that folks! :)
> fix(pages.tests.js): increases test timeout

- .circleci/config.yml
> feat(ci): diff test blocks publish and shares test file

- package-lock.json
- package.json
> chore(request): replace request by helix-fetch

- test/smoke/homepage.smoke.js
Depends on https://github.com/adobe/helix-publish/pull/564
> Test for new Helix Publish Feature

- src/embed_html.htl
> fix(embed): typo

- vcl/extensions.vcl
fixes #424
needs https://github.com/adobe/helix-dispatch/pull/329 to be in place
> fix(vcl): revert caching directive for dispatch

- test/pages/pages.test.js
> feat(pages.test.js): add documentation

- .circleci/config.yml
This reverts commit 88603a2d899115a9a77224a316ade76031ae23d9.
> Revert "feat(pages.test.js): remove theblog-tests (#441)"

- .circleci/config.yml
> chore(ci): publish version as a parameter and smoke tests only

- .circleci/config.yml
Fix #142 
certificates are now up-to-date, tests should be able to run.
> chore(ci): increase number of test sites

- src/html.pre.js
- test/unit/html.pre.test.js
> fix(seo): avoid markup in meta description (#501)

- test/pages/pages.test.js
Fix #50 
This addresses 2 issues:
- make a code execution failure visible to the CI - since the tests are computed, this is important
- fix the code to behave as expected
> chore(test): fix the diff tests

- htdocs/scripts.js
- htdocs/styles.css
> feat(css): suppress layout shift

- test/pages/pages.test.js
> chore(ci): add more logging to get track of failing tests

- src/utils.js
> feat(src/util.js): force release

- test/unit/sidekick.test.js
- test/unit/sidekick/config-plugin.html
- tools/sidekick/app.css
- tools/sidekick/app.js
Fix #548 
Fix #549 
Fix #552 
Fix #554
> Sidekick fixes and enhancements

- README.md
> chore(readme): Add branch URL convention to Readme

- tools/sidekick/app.js
> fix(sidekick): do not try to reuse opener (#565)

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> Sidekick enhancements and fixes

- tools/sidekick/app.js
> feat(sidekick): preview to cycle inner and outer cdn

- test/unit/sidekick.test.js
- tools/sidekick/app.css
- tools/sidekick/app.js
> feat(sidekick): share button

- docs/sidekick-api.md
- package-lock.json
- package.json
- test/unit/sidekick.test.js
- test/unit/sidekick/add-plugins.html
- test/unit/sidekick/config-legacy.html
- test/unit/sidekick/config-plugin-host.html
- test/unit/sidekick/edit-production.html
- test/unit/sidekick/edit-staging.html
- test/unit/sidekick/preview-gdrive.html
- test/unit/sidekick/preview-onedrive.html
- test/unit/sidekick/publish-no-host.html
- test/unit/sidekick/publish-staging.html
- tools/sidekick/app.css
- tools/sidekick/app.js
- tools/sidekick/index.md
Fix #580
Fix #581 
Fix #579 
Fix #587
Fix #593
> Sidekick patch

- tools/sidekick/app.js
Fix #596 
Would love to extend the unit tests for this area but did not find any... I feel it is not so easy. Any advice @rofe ?
Can be manually tested on: 
https://theblog-adobe.hlx-6.page/
https://theblog--adobe.hlx-6.page/
with bookmarklet:
```
javascript:/*%20**%20Helix%20Sidekick%20Bookmarklet%20**%20*/(()%20%3D%3E%20%7Bif(!window.hlxSidekick)%7Bwindow.hlxSidekickConfig%3D%7B%22project%22:%22Blog%22,%22host%22:%22blog.adobe.com%22,%22owner%22:%22adobe%22,%22repo%22:%22theblog%22,%22ref%22:%22master%22%7D%3Bdocument.head.appendChild(document.createElement(%22script%22)).src%3D%22https://www.hlx-6.page/tools/sidekick/app.js%22%3B%7Delse%7Bwindow.hlxSidekick.toggle()%3B%7D%7D)()%3B
```
> feat(sidekick): make Sidekick compliant with Helix URL scheme

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> fix(sidekick): fix inner cdn only use case

- test/unit/sidekick.test.js
- tools/sidekick/app.js
Fix #603
Added a unit test to make sure all known cases are covered. For now, this requires to copy / paste the function, we'll fix that once we find a good way to split the sidekick code.
> fix(sidekick): fix new location resolution

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> fix(sidekick): no more redirect to prod after publish

- test/unit/sidekick.test.js
> Fix sidekick tests

- test/unit/sidekick.test.js
- tools/sidekick/app.css
> feat(sidekick): increase z-index

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> fix(sidekick): remove outer cdn probe (cors)

- test/pages/pages.test.js
> test(diff): retry fetching for diff tests up to three times

- .circleci/config.yml
See https://github.com/adobe/theblog-tests/pull/32
> chore: switch to main branch of theblog-tests

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> fix(sidekick): purge directory index (#648)

- test/unit/sidekick.test.js
Much more stable and also quicker!
> test(sidekick): refactor timeout to promise based

- test/unit/sidekick.test.js
- tools/sidekick/app.js
Use Fastly for purging instead of I/O Runtime directly.
> feat(sidekick): publish to purge via fastly

- test/unit/sidekick.test.js
- tools/sidekick/app.js
Bringing back the working parts of #669 to help fix https://github.com/adobe/theblog/issues/589
> feat(sidekick): add publish() member for reuse by custom plugins

- src/html.pre.js
- src/utils.js
- test/unit/fixtures/page-block-1-col.html
- test/unit/fixtures/page-block-1-col.md
- test/unit/fixtures/page-block-2-col.html
- test/unit/fixtures/page-block-2-col.md
- test/unit/rendering.test.js
> feat: inplement server side blocks handling

- release/deploy.sh
> fix(deploy): use release version in deploy script

- test/unit/sidekick.test.js
- tools/sidekick/app.js
Fix #718 (and make directory purging more resilient)
> feat(sidekick): purge with and without extension as well as .md

- helix-config.yaml
> fix(config): fix 404 for static files in breaking branch

- .circleci/config.yml
- test/unit/sidekick.test.js
- test/unit/sidekick/reload-staging.html
- tools/sidekick/app.css
- tools/sidekick/app.js
> feat(sidekick): reload plugin

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> fix(sidekick): reload button not reliable

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> fix(sidekick): include branch name in host when purging

- src/html.htl
- src/html.pre.js
- test/unit/html.pre.test.js
> feat(seo): use meta image from block

- src/extract-metadata.js
- src/utils.js
- test/unit/html.pre.test.js
Meta image cannot be relative URL
> feat(blob): adjust to rootless image paths

- package-lock.json
- package.json
this version has built-in retries
> fix(deploy): bump helix-deploy version

- tools/sidekick/app.js
> fix(sidekick): reload fails without production host

- vcl/extensions.vcl
toggles the switch provided in https://github.com/adobe/helix-publish/pull/786
> fix(vcl): disable caching of HTML

- src/extract-metadata.js
- test/unit/fixtures/page-metadata-block-hero.html
- test/unit/fixtures/page-metadata-block-hero.md
- test/unit/rendering.test.js
> fix(meta): hero image is wrong

- test/unit/sidekick.test.js
- tools/sidekick/app.js
relative depdencies support for sidekick
> feat(sidekick): support relative dependency URLs

- test/unit/sidekick.test.js
- test/unit/sidekick/is-dev.html
- tools/sidekick/app.js
Fix #780 
Fix #781
(this PR also corrects the condition for the Edit plugin, ensuring no buttons are rendered without the appropriate config)
> feat(sidekick): show reload button on localhost

- src/html.htl
- test/unit/fixtures/page-metadata-block.html
> fix(seo): meta title is not document title

- cgi-bin/feed.js
- test/unit/feed.test.js
> fix(feed): support leading slash

- .circleci/config.yml
Fix https://github.com/adobe/helix-pages/issues/790
> feat(ci): hard purge test domain

- tools/sidekick/index.md
See https://github.com/adobe/project-helix/issues/534
> fix(sidekick): encode from param

- src/extract-metadata.js
- test/unit/fixtures/page-metadata-block-multi-ol.html
- test/unit/fixtures/page-metadata-block-multi-ol.md
- test/unit/fixtures/page-metadata-block-multi-p.html
- test/unit/fixtures/page-metadata-block-multi-p.md
- test/unit/fixtures/page-metadata-block-multi-ul.html
- test/unit/fixtures/page-metadata-block-multi-ul.md
- test/unit/rendering.test.js
> feat(meta): add support for metadata with array of values (multiple p or ol/ul)

- src/create-pictures.js
- src/extract-metadata.js
- src/utils.js
- test/unit/fixtures/page-block-1-col.html
- test/unit/fixtures/page-block-1-col.plain.html
- test/unit/fixtures/page-metadata-block-multi-ol.html
- test/unit/fixtures/page-metadata-block-multi-p.html
- test/unit/fixtures/page-metadata-block-multi-ul.html
- test/unit/fixtures/page-metadata-block.html
- test/unit/fixtures/page-metadata-content-blocks.html
- test/unit/html.pre.test.js
- test/unit/rendering.test.js
- test/unit/utils.test.js
> fix(pre): adjust image optimization

- .circleci/config.yml
- helix-config.yaml
- release/deploy-ci.sh
- release/deploy.sh
all dependent services have been deployed to google, so this is the capstone: helix-pages on google cloud functions. For now, the configuration sends 0% of the traffic to google
> feat(deploy): deploy to google

- src/html.pre.js
- test/unit/html.pre.test.js
Fix https://github.com/adobe/helix-pages/issues/844
> fix(html): new rule for description meta

- .github/workflows/purge-code.yaml
- tools/sidekick/app.js
- tools/sidekick/index.md
> feat(sidekick): serve from www.hlx.live

- test/unit/sidekick.test.js
- test/unit/sidekick/reload-staging.html
- tools/sidekick/app.js
> feat(sidekick): always include branch in preview host

- vcl/extensions.vcl
This PR provides 
* support for private github repos: a `X-Github-Token` header is injected if there is a matching entry in the write-only `repo_github_token` dictionary (key: repo, value: github token)
* support for restricting access to helix-pages serving specific repos: If there's a matching entry in the `acl_restricted_repos` dictionary (key: repo, value: acl) the acl will be applied as an IP whitelist.
> feat(extension.vcl): support private gh repos and acls

- vcl/extensions.vcl
> fix(extensions.vcl): don't apply acl filter on PURGE requests

- tools/sidekick/app.js
- tools/sidekick/index.md
> fix(sidekick): byocdn flag always set on update

- tools/sidekick/app.js
> fix(sidekick): endless update loop

- package.json
- src/extract-metadata.js
- test/unit/fixtures/metadata.json
- test/unit/fixtures/page-metadata-content-blocks.html
> feat: simpler glob matching

- package.json
- src/create-page-blocks.js
- src/utils.js
- test/unit/fixtures/page-block-table-in-table.html
- test/unit/fixtures/page-block-table-in-table.md
- test/unit/fixtures/page-block-with-html-table.html
- test/unit/fixtures/page-block-with-html-table.md
- test/unit/fixtures/page-metadata-block-html.html
- test/unit/fixtures/page-metadata-block-html.md
- test/unit/rendering.test.js
- test/unit/utils.test.js
adds support for page blocks in HTML tables
> fix(blocks): add support for page block in tables

- test/unit/sidekick.test.js
- tools/sidekick/app.js
> feat(sidekick): make branch-agnostic

- index.md
> docs: mention how to configure the sidekick

- test/pages/pages.test.js
Should fix the tests - only issue at the moment are the image hashes that vary for unknown reasons.
> fix: attempt to relax the tests by ignoring the image hashes
