adobe/helix-pages

src/html.htl, src/html.pre.js
=> Temporary workaround for ESI cache killer: append query string

htdocs/style.css, src/plain_html.htl
there was a new `div.plain` inserted somewhere along the way, which made the `:empty` pseudo-class not work anymore. it seems that a `font-size: 0` work around was put in place to visually hide the header and footer, which comes with a range of side-effects when the menu needs to be visible.
this PR should get us back to the original intent.
=> empty <header> and <footer> if not there

htdocs/head.html
i think this workaround has the least forward compatibility issues as it exposes the DOM how we expect it to be in the end after the ESI issue has been fixed.
it has a somewhat undesirable flash effect, but i think this should keep reminding to fix #10
=> workaround for lack of ESI silent continue

src/html.htl
as described in #41 i think we should symmetrically add `<main>` into the default helix-pages output
=> adding enclosing main tag

.eslintrc.js
it is necessary for pipeline to reassign `context` values as part of product workflow
=> disabled eslint rule to reassign param

src/idx_json.js, src/idx_json.pipe.js
added `idx_html.pre.js` and `idx_html.htl` to extract necessary elements for new helix-bot feature
=> adding index and table parser for new probot feature

.circleci/config.yml
Fix CLI version to 4.x in order to avoid introducing breaking changes
=> fix(build): use helix-cli@4.x

.circleci/config.yml, .gitignore, .vscode/launch.json, package-lock.json, package.json, test/smoke/homepage.smoke.js, test/smoketester/generic.smoke.js
PR for https://github.com/adobe/helix-pages/issues/8
Creates the necessary circleci config to allow running it/smoke tests on a testing domain for all the configured repo (list is easily extensible by appending another test definition in the `.config.yaml` file). This does:
- deploys the current Helix Pages code to a `hlx-1.page`, `hlx-2.page` or `hlx-3.page` (modulo of the CircleCI build number)
- allows 2 types of job to run:
- repo has its own it/smoke tests: checkout the project, build and run the tests (npm script can be specified in config)
- repo does not have tests: run some basic tests (generic test code inside Helix Pages project). For now, only gets the homepage, check the response status code and checks if `<head>` and `<body>` are present
List of test jobs currently running …
=> Integration Tests "infrastructure"

README.md
tagging this as `fix` so a new deployment will get made, which applies the changes here: https://github.com/adobe/helix-publish/pull/278
=> fix(readme): add CircleCI badge

package.json
`helix-pages` should follow the same package naming convention as the other Helix services.
=> chore(build): follow package naming convention

cgi-bin/sitemap.js, test/unit/sitemap.test.js
When an index definition file `helix-query.yaml` isn't present, the sitemap generation should silently fail, and not report 10 errors per ESincluded page.
=> fix(sitemap): missing helix-query.yaml shouldn't report 500

src/html.pre.js, test/unit/html.pre.test.js
Fix #284 (temporary workaround)
=> fix(seo): workaround: use relative URL for canonical link

src/html.htl, src/html.pre.js, test/unit/html.pre.test.js
See https://github.com/adobe/helix-pages/issues/284#issuecomment-635301308
=> fix(seo): use relative url only in canonical link

src/html.htl, src/html.pre.js, src/utils.js, test/unit/html.pre.test.js, test/unit/sitemap.test.js
Fix #284
Note: we are retiring support for `x-hlx-pages-host` in the process.
=> fix(seo): use hlx-forwarded-host header and switch canonical url back to absolute

.circleci/config.yml
Ensures Diff is actually outputted in CircleCI logs and console! Verify by visiting link below!
https://app.circleci.com/pipelines/github/adobe/helix-pages/1539/workflows/7a3b1952-96c3-4b55-85f4-ab3a20109142/jobs/5250
=> test(pages.test.js): fix diff output

test/smoke/homepage.smoke.js, vcl/extensions.vcl
This PR splits `helix-pages` caching behavior in two modes:
1. developer-mode, where all responses from `helix-dispatch` will remain uncached as before
2. production mode, that caches exactly like a regular Helix website
Developer mode is ideal for making changes to your site quickly and will be enabled when accessing any subdomain of `hlx.page` or `project-helix.page`.
Production mode is meant for running in production and will be enabled when accessing a site using an outer CDN. This means that caching rules like #402 no longer have to be replicated in the outer CDN, but that all customers running Helix Pages with an outer CDN will benefit from centrally managed caching rules.
As a plus, it also means fewer activations for us.
=> Cache in production

cgi-bin/feed.js, test/unit/feed/feed-fstab.txt
Some authors have the audacity not to write well-formed XHTML, which can break the feed. This fix wraps each entry in a CDATA block.
=> fix(feed): wrap feed entries with CDATA

src/html.pre.js, test/unit/html.pre.test.js
HTML class names cannot contain spaces and JSDOM bails when asked to create a classname with a space. By splitting the class list from metadata at a comma, but not a space, we invite errors when class names are space separated
fixes #482
=> fix(html): guard against spaces in class names

.circleci/config.yml
the workflow id is stable and available through the API to the triggering job (e.g. helix-publish) so that branch-specific tests can be run there. That way I can not just do regression tests, but test new helix-publish features without the catch-22 of having to have them either in helix-pages master or helix-publish master.
=> ci(smoke): use the circle ci workflow id to calculate test domain

.circleci/config.yml
=> ci(smoke): use pipeline number instead of workflow id for domain calculation

src/html.pre.js, test/unit/html.pre.test.js
Fix #411 
Backward compatible way to support JPG as default meta image. The logic is now:
- `helix-pipeline` tries to extract a suitable image from the content
- _[NEW]_ if no meta image was found in the content, look for a `default-meta-image.jpg` in the repo
- fall back to `default-meta-image.png`
- if the repo doesn't have its own `default-meta-image.png` overlay , [this one](https://www.hlx.page/default-meta-image.png) from `helix-pages` will be served
=> feat(seo): support jpg as default meta image

.circleci/config.yml, htdocs/head.html, test/pages/pages.test.js, vcl/extensions.vcl
Fix #513
2 majors changes:
- VCL: if `owner` and `repo` is present in the url but no `branch/ref`, default the `ref` to `master`. This was the case before but only because the `ref` defaults to helix-pages `branch`, i.e. `master`.
- Update the branch in `helix-config.yaml` prior to hlx publish so that the VCL code knows which is the current helix-pages `branch` to use and not only for the `code` part (`content` and `static`)
I put the PR in draft just to make sure it does not get merged before MAX.
=> chore(test): changes in static files are not tested

.circleci/config.yml, package.json, test/pages/pages.test.js
- clean up fetching of original and test content
- add fetch options for original and test
- use queue to only fetch 4 pages concurrently
- improve error handling and logging
- add support for `x-ow-version-lock` header to be passed via `$TEST_VERSION_LOCK`
- add 1 hard coded url from theblog.
=> feat(test): add support for version lock in diff tests

src/html.pre.js, test/unit/html.pre.test.js
=> feat(seo): add fastly io params to meta image url

test/unit/sidekick.test.js, test/unit/sidekick/config-plugin-host.html, tools/sidekick/app.js
This allows developers to load plugins from localhost during development, and customers to reuse centrally hosted plugins across multiple projects.
=> feat(sidekick): allow loading plugins from a fixed host

test/smoke/homepage.smoke.js, test/smoke/test-content.smoke.js
we are often seeing intermittent failures in the smoke tests because the smoke test action is not ready yet or times out. This is a simple fix that will retry each request up to three times, to increase the chance of a 200 so that we don't have to wait another 5 minutes to run the entire test suite just because one request failed.
=> test(smoke): retry smoke tests three times

test/pages/pages.test.js
Improve the error handling: if `dumpDOM` can fail including it in the `try/catch`.
=> chore(test): improve error handling

helix-config.yaml
depends on https://github.com/adobe/helix-publish/pull/704 and is probably broken. The `universal` strain can only be selected via header, so there is little risk of breaking things until you ask for it
=> feat(helix): try using the universal runtime

test/unit/sidekick.test.js
Sidekick tests tend to run into default timeout of `beforeEach()`.
=> Sidekick test timeouts

helix-config.yaml, release/deploy-ci.sh, release/deploy.sh, release/update-config.js
fixes #675
Note: I marked it as `chore` so that we don't deploy a new helix pages version. once merged into master, I will publish manually to fastly.
=> chore(cfg): enable universal strain and preflights

test/unit/sidekick.test.js
Prevent errors like https://app.circleci.com/pipelines/github/adobe/helix-pages/3049/workflows/f9b539a9-8262-4d6a-9fa6-096261355891/jobs/13875
=> test(sidekick): add delay to load css test

test/unit/sidekick.test.js
Fix the timeout issues.
Skipping 5 tests for now since opening a new tab do not allow to intercept the requests (see https://github.com/puppeteer/puppeteer/issues/3667). Will work then on a different solution:
1. use real working pages (no intercept but at least, no long waiting 404s)
2. use something else than pupeteer (playwright ?)
3. keep skipped for now
=> chore(tests): Fix sidekick timeouts

index.md
Add a link to indexing how-to document
=> docs: add link to indexing how-to

test/unit/sidekick.test.js
Response to recent new Sidekick failing tests:
```
1 test failed out of 60
Test sidekick bookmarklet Publish thoroughly purges directories
=> chore(test): Another attempt to make the Sidekick tests more reliable

helix-config.yaml, package-lock.json, package.json, release/deploy-ci.sh, release/deploy.sh
This PR creates two new strains, each using a different gateway host (`helix-pages.anywhere.run` and `helix-pages-ci.anywhere.run`) that will dynamically switch between runtimes.
The old `universal` strain stays as is
=> improve universal deployment

cgi-bin/feed.js
As a precautionary measure HTTP/2 had been disabled in order to avoid issues related to the runtime migration to Azure. We've since re-implemented the http client (fetch) and now it's time to re-enable HTTP/2.
=> fix: re-enable http/2

helix-config.yaml
A smaller, less impactful change than #712, but something that we can apply now.
=> fix(deploy): use separate universal subdomain

package.json
New pipeline step will start caching md/docx files, but we currently have no customer accessible mechanism to purge this cache when previewing.
see https://github.com/adobe/helix-pages/pull/720
=> chore(deps): downgrade pipeline until other building blocks are ready

.circleci/config.yml
so that we can pull it automatically in workflows that are calling the integration tests via API
=> ci(integration): store results of hlx publish command as junit.xml

src/extract-metadata.js, src/html.htl, test/unit/fixtures/page-metadata-block.html, test/unit/fixtures/page-metadata-block.md, test/unit/html.pre.test.js
=> Metadata block: support line-separated lists and arbitrary meta tags

src/extract-metadata.js, src/utils.js, test/unit/html.pre.test.js
~~Removing `.` to in absolute path (works but ugly)~~
Resolve images starting with `./` relative to the path of the containing page.
=> feat(blob): adjust to rootless image paths

test/pages/pages.test.js
"expected" is the original DOM, i.e. the version from `hlx.page`.
"actual" is the tested DOM, i.e. the version from `hlx-X.page`.
=> chore(test): diff tests - swap expected and actual

docs/sitemap.md, index.md
It no longer works with modern indices.
=> chore: deprecate legacy sitemap documentation

release/deploy-ci.sh
Smoke tests init is failing from time to time with error: 
```
--: updating package on Google ...
--: updating app (package) parameters ...
Using existing secret
error: Google - ENOENT: no such file or directory, open '********************************'
error: aborted due to errors during updatePackage
```
=> fix(ci): fix failing smoke tests init

tools/sidekick/app.js
=> fix(sidekick): share url missing byocdn flag

tools/sidekick/app.js
Redirect to `/` instead of `/index`
=> feat(sidekick): suppress /index from webUrl in .lnk report

index.md
- use latest Helix host name
- use Helix URL with branch/ref
- omit `.html` extension
- also work with GH url without path (defaults to `/README`)
- open Helix url in new window
=> docs: update homepage to latest best practices [skip ci]

test/pages/pages.test.js
The purge helps getting the latest version of the html which seems to be cached from time to time. Still not 100% but re-playing the diff_test usually fix the issue after one or 2 retries.
=> chore: restore all the diff tests and add a purge

.eslintignore
=> chore(lint): ignore sidekick
